*** Starting uWSGI 2.0.13.1 (64bit) on [Fri Aug 26 15:14:22 2016] ***
compiled with version: 4.8.4 on 26 August 2016 15:11:35
os: Linux-3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016
nodename: ip-172-31-54-228
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/BlackBelt
detected binary path: /home/ubuntu/BlackBelt/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7862
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address blackbelt.sock fd 3
Python version: 2.7.6 (default, Jun 22 2015, 18:01:27)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1fe9050
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 436560 bytes (426 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1fe9050 pid: 13842 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 13842)
spawned uWSGI worker 1 (pid: 13846, cores: 1)
spawned uWSGI worker 2 (pid: 13847, cores: 1)
spawned uWSGI worker 3 (pid: 13848, cores: 1)
spawned uWSGI worker 4 (pid: 13849, cores: 1)
spawned uWSGI worker 5 (pid: 13850, cores: 1)
[pid: 13846|app: 0|req: 1/1] 12.207.19.98 () {40 vars in 663 bytes} [Fri Aug 26 15:16:59 2016] GET / => generated 2147 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 81 bytes (2 switches on core 0)
[pid: 13847|app: 0|req: 1/2] 12.207.19.98 () {40 vars in 657 bytes} [Fri Aug 26 15:16:59 2016] GET /static/css/stylesheet.css => generated 233 bytes in 4 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 13848|app: 0|req: 1/3] 12.207.19.98 () {40 vars in 614 bytes} [Fri Aug 26 15:16:59 2016] GET /favicon.ico => generated 233 bytes in 4 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 13846|app: 0|req: 2/4] 12.207.19.98 () {50 vars in 881 bytes} [Fri Aug 26 15:17:01 2016] POST /login => generated 209 bytes in 7 msecs (HTTP/1.1 302) 4 headers in 326 bytes (1 switches on core 0)
[pid: 13847|app: 0|req: 2/5] 12.207.19.98 () {46 vars in 924 bytes} [Fri Aug 26 15:17:01 2016] GET / => generated 2232 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 161 bytes (1 switches on core 0)
[pid: 13846|app: 0|req: 3/6] 12.207.19.98 () {40 vars in 657 bytes} [Fri Aug 26 15:17:02 2016] GET /static/css/stylesheet.css => generated 233 bytes in 1 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "./system/core/controller.py", line 36, in dispatch_request
    return action(*args, **kwargs)
  File "./app/controllers/Users.py", line 20, in register
    output = self.models['User'].register(request.form)
  File "./app/models/User.py", line 70, in register
    if len(self.db.query_db(query, data)) > 0:
  File "./system/db/drivers/_mysql.py", line 29, in _query_db
    result = db.session.execute(text(query), data)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1023, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
    engine, execution_options)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'blackbeltdb'")
[pid: 13848|app: 0|req: 2/7] 12.207.19.98 () {50 vars in 889 bytes} [Fri Aug 26 15:17:13 2016] POST /register => generated 0 bytes in 27 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[pid: 13846|app: 0|req: 4/8] 12.207.19.98 () {44 vars in 729 bytes} [Fri Aug 26 15:18:27 2016] GET / => generated 2147 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 13850|app: 0|req: 1/9] 12.207.19.98 () {42 vars in 688 bytes} [Fri Aug 26 15:18:27 2016] GET /static/css/stylesheet.css => generated 233 bytes in 4 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 13846|app: 0|req: 5/10] 12.207.19.98 () {50 vars in 881 bytes} [Fri Aug 26 15:18:29 2016] POST /login => generated 209 bytes in 1 msecs (HTTP/1.1 302) 4 headers in 326 bytes (1 switches on core 0)
[pid: 13849|app: 0|req: 1/11] 12.207.19.98 () {46 vars in 924 bytes} [Fri Aug 26 15:18:29 2016] GET / => generated 2232 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 161 bytes (1 switches on core 0)
[pid: 13846|app: 0|req: 6/12] 12.207.19.98 () {40 vars in 657 bytes} [Fri Aug 26 15:18:29 2016] GET /static/css/stylesheet.css => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "./system/core/controller.py", line 36, in dispatch_request
    return action(*args, **kwargs)
  File "./app/controllers/Users.py", line 31, in login
    output = self.models['User'].login(request.form)
  File "./app/models/User.py", line 26, in login
    user = self.db.query_db(query, data)
  File "./system/db/drivers/_mysql.py", line 29, in _query_db
    result = db.session.execute(text(query), data)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1023, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
    engine, execution_options)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/ubuntu/BlackBelt/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'blackbeltdb'")
[pid: 13847|app: 0|req: 3/13] 12.207.19.98 () {50 vars in 881 bytes} [Fri Aug 26 15:18:34 2016] POST /login => generated 0 bytes in 22 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
